<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <PlatformTarget>x64</PlatformTarget>
    <RootNamespace>TripleDetection</RootNamespace>
    <AssemblyName>TripleDetection</AssemblyName>
    <VmInstallPath>C:\Program Files\VisionMaster4.2.0</VmInstallPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Prism.DryIoc" Version="8.1.97" />
    <PackageReference Include="EntityFramework" Version="6.4.4" />
    <PackageReference Include="System.Data.SQLite" Version="1.0.118" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NModbus" Version="2.1.0" />
  </ItemGroup>

  <!-- VisionMaster SDK DLLs -->
  <ItemGroup>
    <Reference Include="VM.Core">
      <HintPath>$(VmInstallPath)\Development\V4.x\ComControls\Assembly\VM.Core.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="VM.PlatformSDKCS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=c1484a72052ee3d4, processorArchitecture=MSIL">
      <HintPath>$(VmInstallPath)\Development\V4.x\Libraries\win64\C#\VM.PlatformSDKCS.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="iMVS-6000PlatformSDKCS">
      <HintPath>$(VmInstallPath)\Development\V4.x\Libraries\win64\C#\iMVS-6000PlatformSDKCS.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="GlobalVariableModuleCs">
      <HintPath>Infrastructure\libs\VisionMaster\GlobalVariableModuleCs.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="VMControls.BaseInterface">
      <HintPath>$(VmInstallPath)\Development\V4.x\ComControls\Assembly\VMControls.BaseInterface.dll</HintPath>
      <HintPath>$(VmInstallPath)\Development\V4.x\ComControls\Assembly\VMControls.Interface.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="VMControls.RenderInterface">
      <HintPath>$(VmInstallPath)\Development\V4.x\ComControls\Assembly\VMControls.RenderInterface.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="VMControls.Winform.Release">
      <HintPath>$(VmInstallPath)\Development\V4.x\ComControls\Assembly\VMControls.Winform.Release.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="VMControls.WPF.Release">
      <HintPath>$(VmInstallPath)\Development\V4.x\ComControls\Assembly\VMControls.WPF.Release.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Apps.BaseData">
      <HintPath>$(VmInstallPath)\Development\V4.x\ComControls\Assembly\Apps.BaseData.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Apps.ColorFun">
      <HintPath>$(VmInstallPath)\Development\V4.x\ComControls\Assembly\Apps.ColorFun.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Apps.Data">
      <HintPath>Infrastructure\libs\Apps.Data.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Apps.ErrorCode">
      <HintPath>Infrastructure\libs\Apps.ErrorCode.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Apps.Interface">
      <HintPath>Infrastructure\libs\Apps.Interface.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Apps.Localization">
      <HintPath>Infrastructure\libs\Apps.Localization.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Apps.Log">
      <HintPath>Infrastructure\libs\Apps.Log.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Apps.PcUI">
      <HintPath>$(VmInstallPath)\Development\V4.x\ComControls\Assembly\Apps.PcUI.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Apps.UIData">
      <HintPath>Infrastructure\libs\Apps.UIData.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Apps.UIHelper">
      <HintPath>Infrastructure\libs\Apps.UIHelper.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Apps.XmlParser">
      <HintPath>$(VmInstallPath)\Development\V4.x\ComControls\Assembly\Apps.XmlParser.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Apps.XmlUI">
      <HintPath>$(VmInstallPath)\Development\V4.x\ComControls\Assembly\Apps.XmlUI.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="DirectoryBrowser">
      <HintPath>$(VmInstallPath)\Development\V4.x\ComControls\Assembly\DirectoryBrowser.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Frontend.Base">
      <HintPath>$(VmInstallPath)\Development\V4.x\ComControls\Assembly\Frontend.Base.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="FrontendUI.WPF">
      <HintPath>$(VmInstallPath)\Development\V4.x\ComControls\Assembly\FrontendUI.WPF.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="GateWay.Base.Xml">
      <HintPath>$(VmInstallPath)\Development\V4.x\ComControls\Assembly\GateWay.Base.Xml.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="GateWay.Compress">
      <HintPath>$(VmInstallPath)\Development\V4.x\ComControls\Assembly\GateWay.Compress.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="GateWay.Control">
      <HintPath>$(VmInstallPath)\Development\V4.x\ComControls\Assembly\GateWay.Control.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="GateWay.CostomDialog">
      <HintPath>$(VmInstallPath)\Development\V4.x\ComControls\Assembly\GateWay.CostomDialog.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="GateWay.Data">
      <HintPath>$(VmInstallPath)\Development\V4.x\ComControls\Assembly\GateWay.Data.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Mvvm">
      <HintPath>$(VmInstallPath)\Development\V4.x\ComControls\Assembly\Mvvm.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="System.Windows.Interactivity">
      <HintPath>Infrastructure\libs\System.Windows.Interactivity.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="VM.Compress">
      <HintPath>Infrastructure\libs\VM.Compress.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="VM.Controls">
      <HintPath>Infrastructure\libs\VM.Controls.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="VM.ExternalCall">
      <HintPath>Infrastructure\libs\VM.ExternalCall.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="VM.Framework.Container">
      <HintPath>Infrastructure\libs\VM.Framework.Container.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="VM.Util">
      <HintPath>Infrastructure\libs\VM.Util.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="VM.Utility">
      <HintPath>Infrastructure\libs\VM.Utility.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="VMControls.Interface">
      <HintPath>Infrastructure\libs\VMControls.Interface.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="log4net">
      <HintPath>Infrastructure\libs\log4net.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.Core" />
    <Reference Include="System.Data" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Deployment" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="WindowsBase" />
    <Reference Include="System.Xaml" />
    <Reference Include="WindowsFormsIntegration" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Config\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Presentation\Resources\Styles.xaml" />
  </ItemGroup>
</Project>